/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as AttentionRouteImport } from './routes/attention'
import { Route as BriefRouteImport } from './routes/brief'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as DataLayerRouteImport } from './routes/data-layer'
import { Route as DataQualityRouteImport } from './routes/data-quality'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as LivelihoodsRouteImport } from './routes/livelihoods'
import { Route as MapRouteImport } from './routes/map'
import { Route as NationalRouteImport } from './routes/national'
import { Route as OutcomesRouteImport } from './routes/outcomes'
import { Route as AgenciesIndexRouteImport } from './routes/agencies.index'
import { Route as AgenciesAgencyNameRouteImport } from './routes/agencies.$agencyName'
import { Route as HousingIndexRouteImport } from './routes/housing.index'
import { Route as HousingHousingIdRouteImport } from './routes/housing.$housingId'
import { Route as InvestmentIndexRouteImport } from './routes/investment.index'
import { Route as InvestmentProjectIdRouteImport } from './routes/investment.$projectId'
import { Route as LocalitiesIndexRouteImport } from './routes/localities.index'
import { Route as LocalitiesLocalityIdRouteImport } from './routes/localities.$localityId'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as RecordsRecordIdRouteImport } from './routes/records.$recordId'
import { Route as SchemesIndexRouteImport } from './routes/schemes.index'
import { Route as SchemesSchemeNameRouteImport } from './routes/schemes.$schemeName'
import { Route as SignalsIndexRouteImport } from './routes/signals.index'
import { Route as SignalsSignalIdRouteImport } from './routes/signals.$signalId'
import { Route as WardsIndexRouteImport } from './routes/wards.index'
import { Route as WardsWardIdRouteImport } from './routes/wards.$wardId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const AttentionRoute = AttentionRouteImport.update({
  id: '/attention',
  path: '/attention',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefRoute = BriefRouteImport.update({
  id: '/brief',
  path: '/brief',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const DataLayerRoute = DataLayerRouteImport.update({
  id: '/data-layer',
  path: '/data-layer',
  getParentRoute: () => rootRouteImport,
} as any)
const DataQualityRoute = DataQualityRouteImport.update({
  id: '/data-quality',
  path: '/data-quality',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const LivelihoodsRoute = LivelihoodsRouteImport.update({
  id: '/livelihoods',
  path: '/livelihoods',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const NationalRoute = NationalRouteImport.update({
  id: '/national',
  path: '/national',
  getParentRoute: () => rootRouteImport,
} as any)
const OutcomesRoute = OutcomesRouteImport.update({
  id: '/outcomes',
  path: '/outcomes',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenciesIndexRoute = AgenciesIndexRouteImport.update({
  id: '/agencies/',
  path: '/agencies/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenciesAgencyNameRoute = AgenciesAgencyNameRouteImport.update({
  id: '/agencies/$agencyName',
  path: '/agencies/$agencyName',
  getParentRoute: () => rootRouteImport,
} as any)
const HousingIndexRoute = HousingIndexRouteImport.update({
  id: '/housing/',
  path: '/housing/',
  getParentRoute: () => rootRouteImport,
} as any)
const HousingHousingIdRoute = HousingHousingIdRouteImport.update({
  id: '/housing/$housingId',
  path: '/housing/$housingId',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentIndexRoute = InvestmentIndexRouteImport.update({
  id: '/investment/',
  path: '/investment/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentProjectIdRoute = InvestmentProjectIdRouteImport.update({
  id: '/investment/$projectId',
  path: '/investment/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalitiesIndexRoute = LocalitiesIndexRouteImport.update({
  id: '/localities/',
  path: '/localities/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalitiesLocalityIdRoute = LocalitiesLocalityIdRouteImport.update({
  id: '/localities/$localityId',
  path: '/localities/$localityId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsRecordIdRoute = RecordsRecordIdRouteImport.update({
  id: '/records/$recordId',
  path: '/records/$recordId',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemesIndexRoute = SchemesIndexRouteImport.update({
  id: '/schemes/',
  path: '/schemes/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemesSchemeNameRoute = SchemesSchemeNameRouteImport.update({
  id: '/schemes/$schemeName',
  path: '/schemes/$schemeName',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalsIndexRoute = SignalsIndexRouteImport.update({
  id: '/signals/',
  path: '/signals/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalsSignalIdRoute = SignalsSignalIdRouteImport.update({
  id: '/signals/$signalId',
  path: '/signals/$signalId',
  getParentRoute: () => rootRouteImport,
} as any)
const WardsIndexRoute = WardsIndexRouteImport.update({
  id: '/wards/',
  path: '/wards/',
  getParentRoute: () => rootRouteImport,
} as any)
const WardsWardIdRoute = WardsWardIdRouteImport.update({
  id: '/wards/$wardId',
  path: '/wards/$wardId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/attention': typeof AttentionRoute
  '/brief': typeof BriefRoute
  '/compare': typeof CompareRoute
  '/data-layer': typeof DataLayerRoute
  '/data-quality': typeof DataQualityRoute
  '/evidence': typeof EvidenceRoute
  '/livelihoods': typeof LivelihoodsRoute
  '/map': typeof MapRoute
  '/national': typeof NationalRoute
  '/outcomes': typeof OutcomesRoute
  '/agencies/$agencyName': typeof AgenciesAgencyNameRoute
  '/housing/$housingId': typeof HousingHousingIdRoute
  '/investment/$projectId': typeof InvestmentProjectIdRoute
  '/localities/$localityId': typeof LocalitiesLocalityIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/records/$recordId': typeof RecordsRecordIdRoute
  '/schemes/$schemeName': typeof SchemesSchemeNameRoute
  '/signals/$signalId': typeof SignalsSignalIdRoute
  '/wards/$wardId': typeof WardsWardIdRoute
  '/agencies/': typeof AgenciesIndexRoute
  '/housing/': typeof HousingIndexRoute
  '/investment/': typeof InvestmentIndexRoute
  '/localities/': typeof LocalitiesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/schemes/': typeof SchemesIndexRoute
  '/signals/': typeof SignalsIndexRoute
  '/wards/': typeof WardsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/attention': typeof AttentionRoute
  '/brief': typeof BriefRoute
  '/compare': typeof CompareRoute
  '/data-layer': typeof DataLayerRoute
  '/data-quality': typeof DataQualityRoute
  '/evidence': typeof EvidenceRoute
  '/livelihoods': typeof LivelihoodsRoute
  '/map': typeof MapRoute
  '/national': typeof NationalRoute
  '/outcomes': typeof OutcomesRoute
  '/agencies/$agencyName': typeof AgenciesAgencyNameRoute
  '/housing/$housingId': typeof HousingHousingIdRoute
  '/investment/$projectId': typeof InvestmentProjectIdRoute
  '/localities/$localityId': typeof LocalitiesLocalityIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/records/$recordId': typeof RecordsRecordIdRoute
  '/schemes/$schemeName': typeof SchemesSchemeNameRoute
  '/signals/$signalId': typeof SignalsSignalIdRoute
  '/wards/$wardId': typeof WardsWardIdRoute
  '/agencies': typeof AgenciesIndexRoute
  '/housing': typeof HousingIndexRoute
  '/investment': typeof InvestmentIndexRoute
  '/localities': typeof LocalitiesIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/schemes': typeof SchemesIndexRoute
  '/signals': typeof SignalsIndexRoute
  '/wards': typeof WardsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/attention': typeof AttentionRoute
  '/brief': typeof BriefRoute
  '/compare': typeof CompareRoute
  '/data-layer': typeof DataLayerRoute
  '/data-quality': typeof DataQualityRoute
  '/evidence': typeof EvidenceRoute
  '/livelihoods': typeof LivelihoodsRoute
  '/map': typeof MapRoute
  '/national': typeof NationalRoute
  '/outcomes': typeof OutcomesRoute
  '/agencies/$agencyName': typeof AgenciesAgencyNameRoute
  '/housing/$housingId': typeof HousingHousingIdRoute
  '/investment/$projectId': typeof InvestmentProjectIdRoute
  '/localities/$localityId': typeof LocalitiesLocalityIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/records/$recordId': typeof RecordsRecordIdRoute
  '/schemes/$schemeName': typeof SchemesSchemeNameRoute
  '/signals/$signalId': typeof SignalsSignalIdRoute
  '/wards/$wardId': typeof WardsWardIdRoute
  '/agencies/': typeof AgenciesIndexRoute
  '/housing/': typeof HousingIndexRoute
  '/investment/': typeof InvestmentIndexRoute
  '/localities/': typeof LocalitiesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/schemes/': typeof SchemesIndexRoute
  '/signals/': typeof SignalsIndexRoute
  '/wards/': typeof WardsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assets'
    | '/attention'
    | '/brief'
    | '/compare'
    | '/data-layer'
    | '/data-quality'
    | '/evidence'
    | '/livelihoods'
    | '/map'
    | '/national'
    | '/outcomes'
    | '/agencies/$agencyName'
    | '/housing/$housingId'
    | '/investment/$projectId'
    | '/localities/$localityId'
    | '/projects/$projectId'
    | '/records/$recordId'
    | '/schemes/$schemeName'
    | '/signals/$signalId'
    | '/wards/$wardId'
    | '/agencies/'
    | '/housing/'
    | '/investment/'
    | '/localities/'
    | '/projects/'
    | '/schemes/'
    | '/signals/'
    | '/wards/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assets'
    | '/attention'
    | '/brief'
    | '/compare'
    | '/data-layer'
    | '/data-quality'
    | '/evidence'
    | '/livelihoods'
    | '/map'
    | '/national'
    | '/outcomes'
    | '/agencies/$agencyName'
    | '/housing/$housingId'
    | '/investment/$projectId'
    | '/localities/$localityId'
    | '/projects/$projectId'
    | '/records/$recordId'
    | '/schemes/$schemeName'
    | '/signals/$signalId'
    | '/wards/$wardId'
    | '/agencies'
    | '/housing'
    | '/investment'
    | '/localities'
    | '/projects'
    | '/schemes'
    | '/signals'
    | '/wards'
  id:
    | '__root__'
    | '/'
    | '/assets'
    | '/attention'
    | '/brief'
    | '/compare'
    | '/data-layer'
    | '/data-quality'
    | '/evidence'
    | '/livelihoods'
    | '/map'
    | '/national'
    | '/outcomes'
    | '/agencies/$agencyName'
    | '/housing/$housingId'
    | '/investment/$projectId'
    | '/localities/$localityId'
    | '/projects/$projectId'
    | '/records/$recordId'
    | '/schemes/$schemeName'
    | '/signals/$signalId'
    | '/wards/$wardId'
    | '/agencies/'
    | '/housing/'
    | '/investment/'
    | '/localities/'
    | '/projects/'
    | '/schemes/'
    | '/signals/'
    | '/wards/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssetsRoute: typeof AssetsRoute
  AttentionRoute: typeof AttentionRoute
  BriefRoute: typeof BriefRoute
  CompareRoute: typeof CompareRoute
  DataLayerRoute: typeof DataLayerRoute
  DataQualityRoute: typeof DataQualityRoute
  EvidenceRoute: typeof EvidenceRoute
  LivelihoodsRoute: typeof LivelihoodsRoute
  MapRoute: typeof MapRoute
  NationalRoute: typeof NationalRoute
  OutcomesRoute: typeof OutcomesRoute
  AgenciesAgencyNameRoute: typeof AgenciesAgencyNameRoute
  HousingHousingIdRoute: typeof HousingHousingIdRoute
  InvestmentProjectIdRoute: typeof InvestmentProjectIdRoute
  LocalitiesLocalityIdRoute: typeof LocalitiesLocalityIdRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  RecordsRecordIdRoute: typeof RecordsRecordIdRoute
  SchemesSchemeNameRoute: typeof SchemesSchemeNameRoute
  SignalsSignalIdRoute: typeof SignalsSignalIdRoute
  WardsWardIdRoute: typeof WardsWardIdRoute
  AgenciesIndexRoute: typeof AgenciesIndexRoute
  HousingIndexRoute: typeof HousingIndexRoute
  InvestmentIndexRoute: typeof InvestmentIndexRoute
  LocalitiesIndexRoute: typeof LocalitiesIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  SchemesIndexRoute: typeof SchemesIndexRoute
  SignalsIndexRoute: typeof SignalsIndexRoute
  WardsIndexRoute: typeof WardsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attention': {
      id: '/attention'
      path: '/attention'
      fullPath: '/attention'
      preLoaderRoute: typeof AttentionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brief': {
      id: '/brief'
      path: '/brief'
      fullPath: '/brief'
      preLoaderRoute: typeof BriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-layer': {
      id: '/data-layer'
      path: '/data-layer'
      fullPath: '/data-layer'
      preLoaderRoute: typeof DataLayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-quality': {
      id: '/data-quality'
      path: '/data-quality'
      fullPath: '/data-quality'
      preLoaderRoute: typeof DataQualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livelihoods': {
      id: '/livelihoods'
      path: '/livelihoods'
      fullPath: '/livelihoods'
      preLoaderRoute: typeof LivelihoodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/national': {
      id: '/national'
      path: '/national'
      fullPath: '/national'
      preLoaderRoute: typeof NationalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outcomes': {
      id: '/outcomes'
      path: '/outcomes'
      fullPath: '/outcomes'
      preLoaderRoute: typeof OutcomesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agencies/': {
      id: '/agencies/'
      path: '/agencies'
      fullPath: '/agencies/'
      preLoaderRoute: typeof AgenciesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agencies/$agencyName': {
      id: '/agencies/$agencyName'
      path: '/agencies/$agencyName'
      fullPath: '/agencies/$agencyName'
      preLoaderRoute: typeof AgenciesAgencyNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/housing/': {
      id: '/housing/'
      path: '/housing'
      fullPath: '/housing/'
      preLoaderRoute: typeof HousingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/housing/$housingId': {
      id: '/housing/$housingId'
      path: '/housing/$housingId'
      fullPath: '/housing/$housingId'
      preLoaderRoute: typeof HousingHousingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investment/': {
      id: '/investment/'
      path: '/investment'
      fullPath: '/investment/'
      preLoaderRoute: typeof InvestmentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investment/$projectId': {
      id: '/investment/$projectId'
      path: '/investment/$projectId'
      fullPath: '/investment/$projectId'
      preLoaderRoute: typeof InvestmentProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/localities/': {
      id: '/localities/'
      path: '/localities'
      fullPath: '/localities/'
      preLoaderRoute: typeof LocalitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/localities/$localityId': {
      id: '/localities/$localityId'
      path: '/localities/$localityId'
      fullPath: '/localities/$localityId'
      preLoaderRoute: typeof LocalitiesLocalityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records/$recordId': {
      id: '/records/$recordId'
      path: '/records/$recordId'
      fullPath: '/records/$recordId'
      preLoaderRoute: typeof RecordsRecordIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemes/': {
      id: '/schemes/'
      path: '/schemes'
      fullPath: '/schemes/'
      preLoaderRoute: typeof SchemesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemes/$schemeName': {
      id: '/schemes/$schemeName'
      path: '/schemes/$schemeName'
      fullPath: '/schemes/$schemeName'
      preLoaderRoute: typeof SchemesSchemeNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signals/': {
      id: '/signals/'
      path: '/signals'
      fullPath: '/signals/'
      preLoaderRoute: typeof SignalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signals/$signalId': {
      id: '/signals/$signalId'
      path: '/signals/$signalId'
      fullPath: '/signals/$signalId'
      preLoaderRoute: typeof SignalsSignalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wards/': {
      id: '/wards/'
      path: '/wards'
      fullPath: '/wards/'
      preLoaderRoute: typeof WardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wards/$wardId': {
      id: '/wards/$wardId'
      path: '/wards/$wardId'
      fullPath: '/wards/$wardId'
      preLoaderRoute: typeof WardsWardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssetsRoute: AssetsRoute,
  AttentionRoute: AttentionRoute,
  BriefRoute: BriefRoute,
  CompareRoute: CompareRoute,
  DataLayerRoute: DataLayerRoute,
  DataQualityRoute: DataQualityRoute,
  EvidenceRoute: EvidenceRoute,
  LivelihoodsRoute: LivelihoodsRoute,
  MapRoute: MapRoute,
  NationalRoute: NationalRoute,
  OutcomesRoute: OutcomesRoute,
  AgenciesAgencyNameRoute: AgenciesAgencyNameRoute,
  HousingHousingIdRoute: HousingHousingIdRoute,
  InvestmentProjectIdRoute: InvestmentProjectIdRoute,
  LocalitiesLocalityIdRoute: LocalitiesLocalityIdRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  RecordsRecordIdRoute: RecordsRecordIdRoute,
  SchemesSchemeNameRoute: SchemesSchemeNameRoute,
  SignalsSignalIdRoute: SignalsSignalIdRoute,
  WardsWardIdRoute: WardsWardIdRoute,
  AgenciesIndexRoute: AgenciesIndexRoute,
  HousingIndexRoute: HousingIndexRoute,
  InvestmentIndexRoute: InvestmentIndexRoute,
  LocalitiesIndexRoute: LocalitiesIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  SchemesIndexRoute: SchemesIndexRoute,
  SignalsIndexRoute: SignalsIndexRoute,
  WardsIndexRoute: WardsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
