/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as AttentionRouteImport } from './routes/attention'
import { Route as DataQualityRouteImport } from './routes/data-quality'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as MapRouteImport } from './routes/map'
import { Route as OutcomesRouteImport } from './routes/outcomes'
import { Route as AgenciesIndexRouteImport } from './routes/agencies.index'
import { Route as AgenciesAgencyNameRouteImport } from './routes/agencies.$agencyName'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as SchemesIndexRouteImport } from './routes/schemes.index'
import { Route as SchemesSchemeNameRouteImport } from './routes/schemes.$schemeName'
import { Route as WardsIndexRouteImport } from './routes/wards.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const AttentionRoute = AttentionRouteImport.update({
  id: '/attention',
  path: '/attention',
  getParentRoute: () => rootRouteImport,
} as any)
const DataQualityRoute = DataQualityRouteImport.update({
  id: '/data-quality',
  path: '/data-quality',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const OutcomesRoute = OutcomesRouteImport.update({
  id: '/outcomes',
  path: '/outcomes',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenciesIndexRoute = AgenciesIndexRouteImport.update({
  id: '/agencies/',
  path: '/agencies/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenciesAgencyNameRoute = AgenciesAgencyNameRouteImport.update({
  id: '/agencies/$agencyName',
  path: '/agencies/$agencyName',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemesIndexRoute = SchemesIndexRouteImport.update({
  id: '/schemes/',
  path: '/schemes/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemesSchemeNameRoute = SchemesSchemeNameRouteImport.update({
  id: '/schemes/$schemeName',
  path: '/schemes/$schemeName',
  getParentRoute: () => rootRouteImport,
} as any)
const WardsIndexRoute = WardsIndexRouteImport.update({
  id: '/wards/',
  path: '/wards/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/attention': typeof AttentionRoute
  '/data-quality': typeof DataQualityRoute
  '/evidence': typeof EvidenceRoute
  '/map': typeof MapRoute
  '/outcomes': typeof OutcomesRoute
  '/agencies/$agencyName': typeof AgenciesAgencyNameRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/schemes/$schemeName': typeof SchemesSchemeNameRoute
  '/agencies/': typeof AgenciesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/schemes/': typeof SchemesIndexRoute
  '/wards/': typeof WardsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/attention': typeof AttentionRoute
  '/data-quality': typeof DataQualityRoute
  '/evidence': typeof EvidenceRoute
  '/map': typeof MapRoute
  '/outcomes': typeof OutcomesRoute
  '/agencies/$agencyName': typeof AgenciesAgencyNameRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/schemes/$schemeName': typeof SchemesSchemeNameRoute
  '/agencies': typeof AgenciesIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/schemes': typeof SchemesIndexRoute
  '/wards': typeof WardsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/attention': typeof AttentionRoute
  '/data-quality': typeof DataQualityRoute
  '/evidence': typeof EvidenceRoute
  '/map': typeof MapRoute
  '/outcomes': typeof OutcomesRoute
  '/agencies/$agencyName': typeof AgenciesAgencyNameRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/schemes/$schemeName': typeof SchemesSchemeNameRoute
  '/agencies/': typeof AgenciesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/schemes/': typeof SchemesIndexRoute
  '/wards/': typeof WardsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assets'
    | '/attention'
    | '/data-quality'
    | '/evidence'
    | '/map'
    | '/outcomes'
    | '/agencies/$agencyName'
    | '/projects/$projectId'
    | '/schemes/$schemeName'
    | '/agencies/'
    | '/projects/'
    | '/schemes/'
    | '/wards/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assets'
    | '/attention'
    | '/data-quality'
    | '/evidence'
    | '/map'
    | '/outcomes'
    | '/agencies/$agencyName'
    | '/projects/$projectId'
    | '/schemes/$schemeName'
    | '/agencies'
    | '/projects'
    | '/schemes'
    | '/wards'
  id:
    | '__root__'
    | '/'
    | '/assets'
    | '/attention'
    | '/data-quality'
    | '/evidence'
    | '/map'
    | '/outcomes'
    | '/agencies/$agencyName'
    | '/projects/$projectId'
    | '/schemes/$schemeName'
    | '/agencies/'
    | '/projects/'
    | '/schemes/'
    | '/wards/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssetsRoute: typeof AssetsRoute
  AttentionRoute: typeof AttentionRoute
  DataQualityRoute: typeof DataQualityRoute
  EvidenceRoute: typeof EvidenceRoute
  MapRoute: typeof MapRoute
  OutcomesRoute: typeof OutcomesRoute
  AgenciesAgencyNameRoute: typeof AgenciesAgencyNameRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  SchemesSchemeNameRoute: typeof SchemesSchemeNameRoute
  AgenciesIndexRoute: typeof AgenciesIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  SchemesIndexRoute: typeof SchemesIndexRoute
  WardsIndexRoute: typeof WardsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attention': {
      id: '/attention'
      path: '/attention'
      fullPath: '/attention'
      preLoaderRoute: typeof AttentionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-quality': {
      id: '/data-quality'
      path: '/data-quality'
      fullPath: '/data-quality'
      preLoaderRoute: typeof DataQualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outcomes': {
      id: '/outcomes'
      path: '/outcomes'
      fullPath: '/outcomes'
      preLoaderRoute: typeof OutcomesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agencies/': {
      id: '/agencies/'
      path: '/agencies'
      fullPath: '/agencies/'
      preLoaderRoute: typeof AgenciesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agencies/$agencyName': {
      id: '/agencies/$agencyName'
      path: '/agencies/$agencyName'
      fullPath: '/agencies/$agencyName'
      preLoaderRoute: typeof AgenciesAgencyNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemes/': {
      id: '/schemes/'
      path: '/schemes'
      fullPath: '/schemes/'
      preLoaderRoute: typeof SchemesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemes/$schemeName': {
      id: '/schemes/$schemeName'
      path: '/schemes/$schemeName'
      fullPath: '/schemes/$schemeName'
      preLoaderRoute: typeof SchemesSchemeNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wards/': {
      id: '/wards/'
      path: '/wards'
      fullPath: '/wards/'
      preLoaderRoute: typeof WardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssetsRoute: AssetsRoute,
  AttentionRoute: AttentionRoute,
  DataQualityRoute: DataQualityRoute,
  EvidenceRoute: EvidenceRoute,
  MapRoute: MapRoute,
  OutcomesRoute: OutcomesRoute,
  AgenciesAgencyNameRoute: AgenciesAgencyNameRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  SchemesSchemeNameRoute: SchemesSchemeNameRoute,
  AgenciesIndexRoute: AgenciesIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  SchemesIndexRoute: SchemesIndexRoute,
  WardsIndexRoute: WardsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
